### ISSUE TITLE
Awful error on the website

### ISSUE THREAD

**Issue by normalnaismann** [gillkyle/sol-journal#18]
Maybe this isn't the place to talk about this but here it is anyway. I use Chrome, and I pinned a tab of Soljournal, where it stayed on the day I wrote last time. Today I enter the page to write some stuff and I found the last 2 days where clones of what I wrote 3 days ago, completely overwriting my last entries. I thought this was an awful, terrible bug that made me decide to not use this anymore. Please, if this is not the place, you can remove this review but at least address the issue and do not let someone else lose their precious information.

**Comment by gillkyle** [comment]
Hi @normalnaismann, I'm really sorry to hear that your info got overwritten 😔 I wish I could do something to help but I don't think I have any way of seeing a revision history. That's definitely an issue, not one that I've run into yet but thanks for bringing it up. I think a possible solution would be warning before save after a page has sat idle for a while or building better logic into resolving overwriting info if you've written on another device.

Sorry again, it makes me sad to hear something precious to was lost because of an oversight on my part. An alternative that might be worth looking into is Notion which offers many similar features but has more resources for getting some of those edge cases right.
