### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by magicCashew** [gillkyle/sol-journal#31]
I was looking over this and I don't see this so I thought I would confirm.  Is there any support or provision for zero knowledge encryption?

If not is that on a roadmap for consideration?

One of my children was thinking about journaling but was concerned about privacy.  I remembered this project, but was thinking even if you self host you could still be vulnerable to data leaks through bugs, hacks, etc.

**Comment by gillkyle** [comment]
Hey @magicCashew! I did look into it a little bit and really hoped it would be easy or built in somewhere, but didn't have a lot of knowledge of how to implement it myself. I thought it could get tricky and didn't actually try my hand at any sort of implementation figuring I'd mostly just be using it on my own and others would self host (which tends to be the cost in most instances).

That being said, I suppose it is possible with sensitive data being stored elsewhere you run that risk. Maybe JournalBook by trys would be a good alternative to look into? It inspired my project a lot but can't be cross platform because it stores things locally. That might be a good compromise in your case though.

**Comment by gillkyle** [comment]
Here's a link https://github.com/trys/JournalBook

**Comment by magicCashew** [comment]
Okay, cool.  I'll check it out.  Thanks!  I'd love to consider submitting an enhancement, but I am pretty slammed right now.  Maybe if things let up in the near future for me, I could circle back and see if if there's interest.
