### ISSUE TITLE
Build not working

### ISSUE THREAD

**Issue by smamudhan** [gillkyle/sol-journal#7]
Hey there,

I've been trying to deploy this for the past couple of days now; and after 12+ hours of resolving dependencies using npm, finally giving up and using yarn; I now have a successful build. However, it doesn't seem to be working.

I followed setup.md down to the letter and resolved any errors I encountered along the way; but all I get is a bunch of 404's and a site that doesn't work beyond loading the homepage and the login page (none of the links/buttons work) - Please take a look [https://watery-team.surge.sh/](https://watery-team.surge.sh/) I'm not sure what I'm doing wrong here. Any help would be much appreciated.

**Comment by DSchau** [comment]
@smamudhan it looks like you haven't set up your API keys correctly. If you open up the console, there's an illustrative error.

<img width="723" alt="Screen Shot 2019-07-26 at 11 53 32 AM" src="https://user-images.githubusercontent.com/3924690/61974712-10047f80-af9c-11e9-8612-f40ecddd37b4.png">

Perhaps you need to add environment variables (as specified in .env.development) to Surge so that they're exposed to the application? Conversely, you may need an .env.production file so that the _build_ (which is in production mode) generates successfully.

**Comment by gillkyle** [comment]
@DSchau is right, I have a conversation with @smamudhan on Twitter about this. Need to update the SETUP.md to include a note on adding the env variables to the deployment service being used like Netlify or surge.
